import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import forestScene from "../assets/diorama_-_forest_loner.glb";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Forest(props) {
  const forestRef = useRef();
  const { nodes, materials } = useGLTF(forestScene);
  return (
    <group ref={forestRef} {...props}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Water_m_Water2_0.geometry}
          material={materials.m_Water2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Water_m_Water_0.geometry}
          material={materials.m_Water}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WaterRock_m_BigRocks_0.geometry}
          material={materials.m_BigRocks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GroundPlane_m_GroundMossy_0.geometry}
          material={materials.m_GroundMossy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GroundPlane_m_GroundPineNeedles_0.geometry}
          material={materials.m_GroundPineNeedles}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GroundPlane_m_GroundTireTracks_0.geometry}
          material={materials.m_GroundTireTracks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GroundPlane_m_Soil_0.geometry}
          material={materials.m_Soil}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HillRock_m_BigRocks_0.geometry}
          material={materials.m_BigRocks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern1_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern2_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern3_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern4_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern5_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern6_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern7_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern8_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern9_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern10_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern11_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern12_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern13_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern14_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern15_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern16_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern17_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern18_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern19_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern20_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern21_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern22_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern23_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern24_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern25_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern26_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern27_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern28_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern29_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern30_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern31_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern32_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern33_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern34_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern35_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern36_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern37_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern38_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern39_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern40_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern41_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern42_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern43_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern44_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern45_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern46_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern47_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern48_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern49_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern50_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern51_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern52_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern53_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern54_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern55_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern56_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern57_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern58_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern59_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern60_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern61_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern62_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern63_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern64_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern65_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern66_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern67_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern68_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern69_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern70_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern71_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern72_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern73_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern74_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern75_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern76_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern77_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern78_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern79_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern80_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern81_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern82_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fern83_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dead_tree2_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree6_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree6_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree1_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree1_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree2_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree2_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree3_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree3_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree4_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree4_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dead_Tree_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree5_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree5_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dead_Tree1_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass1_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass2_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass3_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass4_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass5_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass6_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass7_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass8_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass9_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass10_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass11_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass12_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass13_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass14_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass15_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass16_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass17_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass18_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass19_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass20_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass21_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass22_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass23_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass24_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass25_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass26_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass27_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass28_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass29_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass30_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass31_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass32_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass33_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass34_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass35_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass36_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass39_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass42_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass43_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass44_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass45_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass46_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass47_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass48_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass49_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass50_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass51_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grass52_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass27_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass26_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass25_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass24_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass23_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass22_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass21_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass20_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass19_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass18_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass17_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass16_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass15_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass14_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass13_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass12_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass11_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass10_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass9_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass8_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass7_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass6_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass5_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass4_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass3_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass2_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass1_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass28_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass29_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass30_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass31_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass32_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass33_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass34_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass35_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass36_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass37_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass38_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass39_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass40_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass41_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass42_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass43_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass44_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass45_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass46_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass47_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass48_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass49_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass50_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass51_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass52_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass53_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass54_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass55_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass56_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass57_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass58_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass59_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass60_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass61_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass62_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass63_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass64_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass65_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass66_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass67_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass68_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass69_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HighGrass70_m_Plants1_0.geometry}
          material={materials.m_Plants1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shed_Roof_m_Shed_Roof_0.geometry}
          material={materials.m_Shed_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shed_Walls_m_House_Walls_0.geometry}
          material={materials.m_House_Walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shed_Skelet_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Sink_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shed_Planks_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Ladder_m_LadderChimneyBarrel_0.geometry}
          material={materials.m_LadderChimneyBarrel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GasCan_m_Jeep_0.geometry}
          material={materials.m_Jeep}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shed_Planks1_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shed_Planks2_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shed_Planks3_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ShotgunShells_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_WoodenChair_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ShotgunShells2_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_WoodenChair1_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ShotgunShells3_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ShotgunShells4_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ShotgunShells5_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Ladder1_m_LadderChimneyBarrel_0.geometry}
          material={materials.m_LadderChimneyBarrel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Ladder2_m_LadderChimneyBarrel_0.geometry}
          material={materials.m_LadderChimneyBarrel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Pallet_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainbarrel_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainbarrel_m_Water2_0.geometry}
          material={materials.m_Water2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainbarrel_m_LadderChimneyBarrel_0.geometry}
          material={materials.m_LadderChimneyBarrel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Lantern_m_House_Uniques1_0.geometry}
          material={materials.m_House_Uniques1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Lantern_m_LanternGlass_0.geometry}
          material={materials.m_LanternGlass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone1_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone2_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone3_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone4_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone5_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone6_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Pallet1_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Pallet2_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone7_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone8_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone9_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_SmallStone10_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Stones_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Walls_m_House_Walls_0.geometry}
          material={materials.m_House_Walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Walls_m_House_Wood2_0.geometry}
          material={materials.m_House_Wood2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Roof_m_House_Roof_0.geometry}
          material={materials.m_House_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Skelet_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Barrel1_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface2_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Door_m_House_Uniques1_0.geometry}
          material={materials.m_House_Uniques1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Window_Sides_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_WindowSmall_Sides_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Door_Sides_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Extra1_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Window_m_House_Uniques1_0.geometry}
          material={materials.m_House_Uniques1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Side_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_WindowSmall_m_House_Uniques1_0.geometry}
          material={materials.m_House_Uniques1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_WindowRaster_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Basement_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Basement_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Basement_m_House_Wood2_0.geometry}
          material={materials.m_House_Wood2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_RainPipeBrokenPiece_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_WindowRaster1_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Extra2_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe1_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Side1_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Side2_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Side3_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder1_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder2_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder3_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder4_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder5_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder6_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder7_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder8_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder9_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder10_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.House_Rainpipe_Holder11_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chimney_m_LadderChimneyBarrel_0.geometry}
          material={materials.m_LadderChimneyBarrel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nail_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog1_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog1_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog2_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog2_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog3_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog3_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog4_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog4_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog5_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog5_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog6_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog6_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog7_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog7_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog8_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog8_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog9_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog9_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog10_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog10_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog11_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog11_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog12_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog12_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog13_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog13_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog14_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog14_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog15_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog15_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog16_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog16_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog17_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog17_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog18_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog18_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog19_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog19_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog20_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog20_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog21_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog21_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog22_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog22_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog23_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog23_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog26_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog26_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog27_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog27_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog28_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog28_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog29_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog29_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog30_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog30_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog31_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog31_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog32_m_TreeBark_0.geometry}
          material={materials.m_TreeBark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WoodLog32_m_House_Trim_0.geometry}
          material={materials.m_House_Trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jeep_Tire_m_Jeep_0.geometry}
          material={materials.m_Jeep}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CliffRock_m_BigRocks_0.geometry}
          material={materials.m_BigRocks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface3_m_Water2_0.geometry}
          material={materials.m_Water2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface4_m_WashingStation_0.geometry}
          material={materials.m_WashingStation}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Washing_StationBig_Bench_m_WashingStation_0.geometry}
          material={materials.m_WashingStation}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Washing_StationTall_Bench_m_WashingStation_0.geometry}
          material={materials.m_WashingStation}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Washing_StationTall_Tub_m_WashingStation_0.geometry}
          material={materials.m_WashingStation}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ShotgunShells1_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shotgun2_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jeep1_m_Jeep_0.geometry}
          material={materials.m_Jeep}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shotgun1_m_Shotgun_0.geometry}
          material={materials.m_Shotgun}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType2_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType4_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType5_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType6_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType7_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType8_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType9_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType10_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType11_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType12_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType13_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType14_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType15_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType16_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType17_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType18_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType19_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType20_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType21_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType22_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType23_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType24_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType3_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType25_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType26_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType27_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType28_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType29_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GrassType30_m_PlantsAndSmoke_0.geometry}
          material={materials.m_PlantsAndSmoke}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock1_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock2_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock3_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock4_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock5_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock6_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock7_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock8_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock9_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock10_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SmallRock11_m_RocksFence_0.geometry}
          material={materials.m_RocksFence}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface5_m_House_Walls_0.geometry}
          material={materials.m_House_Walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface5_m_Shed_Roof_0.geometry}
          material={materials.m_Shed_Roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface5_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DangerSign_m_Signs_0.geometry}
          material={materials.m_Signs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DangerSign_m_House_Trim2_0.geometry}
          material={materials.m_House_Trim2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BearPoster_m_Signs_0.geometry}
          material={materials.m_Signs}
        />
      </group>
    </group>
  );
}

export default Forest;
